"""
AI research report generation (Claude API).

IMPORTANT DESIGN PRINCIPLE — separation of fact and interpretation:
  - Everything fed INTO the model is objective data collected upstream.
  - The model's output is clearly labeled as AI-GENERATED INTERPRETATION.
  - Analyst consensus (if present) is REAL analyst opinion, passed through.

The report never invents numbers: the prompt instructs the model to only
reference figures present in the input data.
"""

import json
import anthropic

import config

SYSTEM_PROMPT = """You are an equity research analyst writing an institutional-style research note.

STRICT RULES:
- Use ONLY the numbers provided in the data. Never invent or estimate figures.
- Clearly separate FACTS (the data given) from INTERPRETATION (your analysis).
- When analyst consensus data is provided, attribute it explicitly to analysts, not to yourself.
- If a data point is missing, say so rather than guessing.
- Be balanced: every thesis must include both a bull case and a bear case.
- No hedging filler. Direct, professional language.
"""

REPORT_TEMPLATE = """Generate a one-page equity research note with these sections:

## Company Snapshot
2-3 sentences: what the company does, sector, market cap context.

## Valuation
Where the stock trades vs peers (use the relative valuation data).
State explicitly whether the multiples imply premium or discount and on which metrics.

## Fundamentals Assessment
Margins, returns on capital, growth, balance sheet — what the numbers say.

## Analyst Consensus (if available)
Real analyst price targets and recent rating actions. Attribute clearly.

## Macro Context (if available)
How the current rate/inflation environment matters for this name.

## Bull Case / Bear Case
3 points each, grounded in the data provided.

## Bottom Line
2-3 sentences. What an investor should focus on. Do NOT give a buy/sell recommendation —
state what the data supports and what the key uncertainties are.

DATA:
{data_json}
"""


def generate_report(payload: dict) -> str:
    """
    payload: dict with keys like fundamentals, price_stats, relative_valuation,
    analyst_data, insider_activity, macro_context.
    Returns markdown report text.
    """
    if not config.ANTHROPIC_API_KEY:
        print("[error] Claude API: ANTHROPIC_API_KEY not set — using template report")
        return _template_report(payload, reason="ANTHROPIC_API_KEY not set")

    try:
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        prompt = REPORT_TEMPLATE.format(data_json=json.dumps(payload, indent=2, default=str))

        last_error = None
        for model in config.CLAUDE_MODELS:
            try:
                msg = client.messages.create(
                    model=model,
                    max_tokens=2000,
                    system=SYSTEM_PROMPT,
                    messages=[{"role": "user", "content": prompt}],
                )
                text = "".join(b.text for b in msg.content if hasattr(b, "text"))
                header = (
                    f"# AI-Generated Research Note — {payload.get('ticker', '')}\n\n"
                    f"*Interpretation generated by {model} from objective data. "
                    f"Analyst consensus figures, where shown, are real analyst opinions.*\n\n"
                )
                return header + text
            except Exception as e:
                last_error = e
                print(f"[error] Claude API failed with model {model}: {e}")
                continue

        print(f"[error] Claude API: all models failed — using template report ({last_error})")
        return _template_report(payload, reason=f"Claude API failed: {last_error}")
    except Exception as e:
        print(f"[error] Claude API: unexpected error — using template report: {e}")
        return _template_report(payload, reason=str(e))


def _template_report(payload: dict, reason: str = "") -> str:
    """Structured report built from collected data when AI is unavailable."""
    ticker = payload.get("ticker", "")
    fundamentals = payload.get("fundamentals") or {}
    price_stats = payload.get("price_stats") or {}
    rel_val = payload.get("relative_valuation") or {}
    macro = payload.get("macro_context") or {}
    analysts = payload.get("analyst_consensus") or {}
    insider = payload.get("insider_activity") or {}
    transcript = payload.get("transcript_analysis") or {}

    lines = [
        f"# Research Note — {ticker}",
        "",
        "*Template report generated from collected data (AI interpretation unavailable).*",
    ]
    if reason:
        lines.append(f"*Reason: {reason}*")
    lines.append("")

    lines.append("## Company Snapshot")
    if fundamentals.get("available") is False:
        lines.append(f"- Data unavailable: {fundamentals.get('note', 'unknown')}")
    else:
        lines.append(f"- **Company:** {fundamentals.get('company_name', 'N/A')}")
        lines.append(f"- **Sector:** {fundamentals.get('sector', 'N/A')} / {fundamentals.get('industry', 'N/A')}")
        lines.append(f"- **Market cap:** {fundamentals.get('market_cap', 'N/A')}")
    lines.append("")

    lines.append("## Price & Performance")
    if price_stats.get("available") is False:
        lines.append(f"- Data unavailable: {price_stats.get('note', 'unknown')}")
    else:
        lines.append(f"- **Last price:** {price_stats.get('last_price', 'N/A')}")
        lines.append(f"- **1Y return:** {price_stats.get('return_1y', 'N/A')}")
        lines.append(f"- **Annualized vol:** {price_stats.get('annualized_volatility', 'N/A')}")
        lines.append(f"- **Max drawdown:** {price_stats.get('max_drawdown', 'N/A')}")
    lines.append("")

    lines.append("## Valuation vs Peers")
    if rel_val.get("available") is False:
        lines.append(f"- Data unavailable: {rel_val.get('note', 'No peer data')}")
    elif not rel_val or len(rel_val) <= 1:
        lines.append("- No relative valuation metrics available.")
    else:
        for metric, vals in rel_val.items():
            if metric == "available" or not isinstance(vals, dict):
                continue
            premium = vals.get("premium_vs_peers")
            direction = "premium" if premium and premium > 0 else "discount"
            lines.append(
                f"- **{metric}:** target {vals.get('target')} vs peer median "
                f"{vals.get('peer_median')} ({direction} {abs(premium or 0):.1%})"
            )
    lines.append("")

    lines.append("## Fundamentals")
    if fundamentals.get("available") is False:
        lines.append(f"- Data unavailable: {fundamentals.get('note', 'unknown')}")
    else:
        for label, key in [
            ("P/E (TTM)", "pe_ttm"), ("EV/EBITDA", "ev_ebitda"), ("Gross margin", "gross_margin"),
            ("Operating margin", "operating_margin"), ("ROE", "roe"), ("Rev growth YoY", "revenue_growth_yoy"),
        ]:
            val = fundamentals.get(key)
            if val is not None:
                lines.append(f"- **{label}:** {val}")
    lines.append("")

    lines.append("## Macro Context")
    if macro.get("available") is False:
        lines.append(f"- Data unavailable: {macro.get('note', 'unknown')}")
    else:
        lines.append(f"- **Fed funds:** {macro.get('fed_funds_rate', 'N/A')}")
        lines.append(f"- **10Y yield:** {macro.get('ten_year_yield', 'N/A')}")
        lines.append(f"- **CPI YoY:** {macro.get('cpi_yoy', 'N/A')}")
        lines.append(f"- **Unemployment:** {macro.get('unemployment_rate', 'N/A')}")
    lines.append("")

    lines.append("## Analyst Consensus")
    if analysts.get("available") is False:
        lines.append(f"- Data unavailable: {analysts.get('note', 'unknown')}")
    else:
        pt = analysts.get("price_target_consensus")
        if pt:
            lines.append(f"- **Price target consensus:** {pt}")
        actions = analysts.get("recent_rating_actions") or []
        if actions:
            lines.append(f"- **Recent rating actions:** {len(actions)} on record")
    lines.append("")

    lines.append("## Insider Activity")
    if insider.get("available") is False:
        lines.append(f"- Data unavailable: {insider.get('note', 'unknown')}")
    else:
        lines.append(f"- **Form 4 filings (6m):** {insider.get('form4_filings_last_6m', 'N/A')}")
    lines.append("")

    if transcript.get("available"):
        lines.append("## Earnings Transcript Highlights")
        lines.append(f"- **Sentiment:** {transcript.get('sentiment', 'N/A')}")
        guidance = transcript.get("management_guidance")
        if guidance:
            lines.append(f"- **Guidance:** {guidance}")
        risks = transcript.get("key_risks") or []
        if risks:
            lines.append(f"- **Key risks:** {', '.join(str(r) for r in risks[:5])}")

    return "\n".join(lines)


def _fallback_report(payload: dict) -> str:
    """Alias for template report (backward compatibility)."""
    return _template_report(payload)


TRANSCRIPT_SYSTEM = """You are an equity research analyst reviewing an earnings call transcript.
Extract structured insights from the transcript only. Do not invent information not present in the text.
Return valid JSON matching the requested schema exactly."""

TRANSCRIPT_PROMPT = """Analyze this earnings call transcript for {ticker}.

Extract:
1. management_guidance — next quarter guidance or outlook (revenue, EPS, margins, or qualitative; null if not stated)
2. key_risks — list of key risks management mentioned
3. sentiment — overall tone: "bullish", "neutral", or "bearish"
4. top_quotes — exactly 3 most important executive quotes, each with "speaker" and "quote"

Return ONLY a JSON object with those keys.

TRANSCRIPT:
{transcript}
"""

PORTFOLIO_BRIEF_SYSTEM = """You are a portfolio strategist writing a concise weekly brief for an investor.
Use only the data provided. Be direct and actionable. No buy/sell recommendations."""

PORTFOLIO_BRIEF_PROMPT = """Write a weekly portfolio brief covering all holdings below.

Include:
- Portfolio overview (composition, notable movers)
- Key themes across holdings
- Risks to watch this week
- 3 bullet points of what matters most

Holdings data:
{data_json}
"""


def _call_claude(system: str, prompt: str, max_tokens: int = 2000) -> str | None:
    if not config.ANTHROPIC_API_KEY:
        print("[error] Claude API: ANTHROPIC_API_KEY not set")
        return None
    try:
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        for model in config.CLAUDE_MODELS:
            try:
                msg = client.messages.create(
                    model=model,
                    max_tokens=max_tokens,
                    system=system,
                    messages=[{"role": "user", "content": prompt}],
                )
                return "".join(b.text for b in msg.content if hasattr(b, "text"))
            except Exception as e:
                print(f"[error] Claude API failed with model {model}: {e}")
                continue
        print("[error] Claude API: all models failed")
        return None
    except Exception as e:
        print(f"[error] Claude API: unexpected error: {e}")
        return None


def _parse_json_response(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())


def analyze_transcript(transcript_text: str, ticker: str) -> dict:
    """
    Extract guidance, risks, sentiment, and top quotes from an earnings transcript.
    Returns structured dict; falls back gracefully without API key.
    """
    try:
        if not transcript_text or len(transcript_text.strip()) < 200:
            note = "Transcript too short to analyze"
            print(f"[error] {note} for {ticker}")
            return {"available": False, "note": note}

        truncated = transcript_text[:120_000]
        if not config.ANTHROPIC_API_KEY:
            note = "ANTHROPIC_API_KEY not set — transcript collected but not analyzed"
            print(f"[error] Claude API: {note}")
            return {"available": False, "note": note, "char_count": len(transcript_text)}

        prompt = TRANSCRIPT_PROMPT.format(ticker=ticker.upper(), transcript=truncated)
        raw = _call_claude(TRANSCRIPT_SYSTEM, prompt, max_tokens=1500)
        if not raw:
            note = "Claude API call failed for transcript analysis"
            print(f"[error] {note} ({ticker})")
            return {"available": False, "note": note}

        parsed = _parse_json_response(raw)
        return {
            "available": True,
            "ticker": ticker.upper(),
            "management_guidance": parsed.get("management_guidance"),
            "key_risks": parsed.get("key_risks", []),
            "sentiment": parsed.get("sentiment", "neutral"),
            "top_quotes": parsed.get("top_quotes", []),
        }
    except json.JSONDecodeError as e:
        note = f"Failed to parse transcript analysis JSON for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}
    except Exception as e:
        note = f"Transcript analysis failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


def generate_portfolio_brief(portfolio_data: list[dict]) -> str:
    """AI weekly brief for all portfolio holdings."""
    try:
        if not portfolio_data:
            return "No portfolio holdings to brief."

        if not config.ANTHROPIC_API_KEY:
            print("[error] Claude API: ANTHROPIC_API_KEY not set — returning data summary brief")
            return _portfolio_brief_template(portfolio_data, reason="ANTHROPIC_API_KEY not set")

        prompt = PORTFOLIO_BRIEF_PROMPT.format(
            data_json=json.dumps(portfolio_data, indent=2, default=str)
        )
        text = _call_claude(PORTFOLIO_BRIEF_SYSTEM, prompt, max_tokens=1500)
        if not text:
            print("[error] Claude API: portfolio brief generation failed — using template")
            return _portfolio_brief_template(portfolio_data, reason="Claude API call failed")
        return f"# Weekly Portfolio Brief\n\n*AI-generated from current holdings and prices.*\n\n{text}"
    except Exception as e:
        print(f"[error] Portfolio brief generation failed: {e}")
        return _portfolio_brief_template(portfolio_data, reason=str(e))


def _portfolio_brief_template(portfolio_data: list[dict], reason: str = "") -> str:
    """Fallback portfolio brief built from holdings data."""
    lines = [
        "# Weekly Portfolio Brief",
        "",
        "*Template brief generated from holdings data (AI unavailable).*",
    ]
    if reason:
        lines.append(f"*Reason: {reason}*")
    lines.append("")

    total_value = sum(p.get("market_value") or 0 for p in portfolio_data)
    total_pnl = sum(p.get("pnl") or 0 for p in portfolio_data)
    lines.append(f"- **Total value:** ${total_value:,.2f}")
    lines.append(f"- **Total P&L:** ${total_pnl:,.2f}")
    lines.append(f"- **Holdings:** {len(portfolio_data)}")
    lines.append("")

    for p in portfolio_data:
        lines.append(
            f"- **{p.get('ticker')}:** {p.get('shares')} shares @ "
            f"${p.get('current_price', 'N/A')} | weight {p.get('weight', 0):.1%} | "
            f"P&L ${p.get('pnl', 0):,.2f}"
        )

    return "\n".join(lines)
